version: '3.8'
services:

  db:
    image: mysql:8.0.29
    container_name: mysql
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: user-docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: smartcookbook
    ports:
      - "3308:3306"
    networks:
      - smartcookbook-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - smartcookbook-network

  kafka:
    image: confluentinc/cp-kafka:7.2.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    networks:
      - smartcookbook-network

  api-smartcookbook:
    image: augustomarques/smartcookbook
    container_name: smart-cookbook
    build: .
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    networks:
      - smartcookbook-network

networks:
  smartcookbook-network:
    driver: bridge