version: '3.4'
services:
  db:
    image: mysql:8.0.23
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: smartcookbook
    ports:
      - "3308:3306"
    networks:
      - smartcookbook-network
  api-smartcookbook:
    image: augustomarques/smartcookbook
    build: .
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=local
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    networks:
      - smartcookbook-network
networks:
  smartcookbook-network:
    driver: bridge