version: '3.4'
services:
  api-smartcookbook:
    image: augustomarques/smartcookbook
    restart: always
    build: .
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - "8080:8080"
    command: mvn spring-boot:run