spring:
  profiles:
    active: ${PROFILE:dev}
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
  jpa:
    open-in-view: false

---

spring:
  profiles: test
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: 1234
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: validate

---

spring:
  profiles: dev
  h2:
    console:
      enabled: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/smartcookbook?useSSL=false&useTimezone=true&serverTimezone=GMT-3
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false