spring:
  profiles:
    active: dev
  h2:
    console:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
  jpa:
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:db;MODE=MySQL;DATABASE_TO_LOWER=TRUEDB_CLOSE_DELAY=-1
    username: sa
    password: 1234
  jpa:
    database: H2
    show-sql: true

---

spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/smartcookbook?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT-3
    username: root
    password: password
  jpa:
    show-sql: true

---

spring:
  profiles: local
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://db:3306/smartcookbook?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT-3
    username: root
    password: docker
  jpa:
    show-sql: false

---

spring:
  profiles: prod
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    url: jdbc:mysql://db-smartcookbook.c8l3ipzqviwg.us-east-2.rds.amazonaws.com:3306/smartcookbook?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT-3
    username: admin
    password: passwordsmartcookbook
  jpa:
    show-sql: false