name: Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    needs: integration-test
    uses: ./.github/workflows/test.yml
    secrets: inherit
    
  docker:
    needs: integration-test
    uses: ./.github/workflows/docker.yml
    secrets: inherit
