name: Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  unit-test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
  
    - name: Unit Test
      run: mvn test
  
  integration-test:
    needs: unit-test
    
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
      
    - name: Integration Test
      run: mvn clean install -DskipUnitTests

  docker:
    needs: integration-test
    uses: ./.github/workflows/docker.yml
    secrets: inherit
